version: '3.7'

services:
  # Main application service
  trothcam:
    image: ${DOCKER_USERNAME}/samryong
    container_name: samryong
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - es
      - mongodb
      - redis  # Redis 컨테이너가 시작될 때까지 대기
    networks:
      - app-network

  # Elasticsearch service
  es:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=backtony
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network

  # Kibana service
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - app-network

  # MongoDB service
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - app-network

  # Redis service
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
