# 로컬 환경에서 사용할 설정 파일
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL} # jdbc:mysql://localhost:3306/samryong
    username: ${SPRING_DATASOURCE_USERNAME} # root
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/samryong
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      uris: http://elasticsearch:9200

kakao:
  client: ${KAKAO_CLIENT_ID} # REST-API 키
  redirect-uri: ${KAKAO_REDIRECT_URI} # 설정해놓은 redirect-uri

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}

nonghyup:
  api:
    access-token: ${NONGHYUP_ACCESS_TOKEN} # 농협 API Access Token
    iscd : ${NONGHYUP_ISCD} # 농협 API ISCD, 기관 코드
    fintech-apsno: "001" # 농협 API FintechApsno, 핀테크 앱 일련번호, 테스트 시 001로 고정
    brdt-brno: ${NONGHYUP_BRDT_BRNO} # 농협 API BrdtBrno, 테스트 예금주 생년월일

cloud:
  aws:
    s3:
      bucket: samryong
      path:
        item: item
        member: member
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}